<a href="https://colab.research.google.com/github/Priyadeb-Barman/billing-software-by-python/blob/main/ds1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!gdown --fuzzy --output iris.csv "https://drive.google.com/file/d/1PEbPxSenrlQKHF1UxYN8Roj4gEftzzCE/view?usp=sharing"

import pandas as pd
df = pd.read_csv('iris.csv')
df.head()

Downloading...
From: https://drive.google.com/uc?id=1PEbPxSenrlQKHF1UxYN8Roj4gEftzzCE
To: /content/iris.csv
100% 3.87k/3.87k [00:00<00:00, 12.7MB/s]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [10]:
from google.colab import drive
drive.mount('/content/drive')

!gdown --fuzzy --output /content/drive/MyDrive/iris.csv "https://drive.google.com/file/d/1PEbPxSenrlQKHF1UxYN8Roj4gEftzzCE/view?usp=sharing"

df = pd.read_csv('/content/drive/MyDrive/iris.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Downloading...
From: https://drive.google.com/uc?id=1PEbPxSenrlQKHF1UxYN8Roj4gEftzzCE
To: /content/drive/MyDrive/iris.csv
100% 3.87k/3.87k [00:00<00:00, 13.1MB/s]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [13]:
!gdown --fuzzy --output stock.csv "https://drive.google.com/file/d/1Qwt8hl35xRBqqEgx7hjfZ6D5ZMAQnWlE/view?usp=sharing"

import pandas as pd
df = pd.read_csv('stock.csv')
df.head()

Downloading...
From: https://drive.google.com/uc?id=1Qwt8hl35xRBqqEgx7hjfZ6D5ZMAQnWlE
To: /content/stock.csv
100% 571/571 [00:00<00:00, 2.35MB/s]

   Year  Month  Interest_Rate  Unemployment_Rate  Stock_Index_Price
0  2017     12           2.75                5.3               1464
1  2017     11           2.50                5.3               1394
2  2017     10           2.50                5.3               1357
3  2017      9           2.50                5.3               1293
4  2017      8           2.50                5.4               1256

In [15]:
from google.colab import drive
drive.mount('/content/drive')

!gdown --fuzzy --output /content/drive/MyDrive/stock.csv "https://drive.google.com/file/d/1Qwt8hl35xRBqqEgx7hjfZ6D5ZMAQnWlE/view?usp=sharing"

df = pd.read_csv('/content/drive/MyDrive/stock.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Downloading...
From: https://drive.google.com/uc?id=1Qwt8hl35xRBqqEgx7hjfZ6D5ZMAQnWlE
To: /content/drive/MyDrive/stock.csv
100% 571/571 [00:00<00:00, 2.17MB/s]

   Year  Month  Interest_Rate  Unemployment_Rate  Stock_Index_Price
0  2017     12           2.75                5.3               1464
1  2017     11           2.50                5.3               1394
2  2017     10           2.50                5.3               1357
3  2017      9           2.50                5.3               1293
4  2017      8           2.50                5.4               1256

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
!wget https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2024-financial-year-provisional/Download-data/annual-enterprise-survey-2024-financial-year-provisional.csv

--2025-08-10 05:49:13--  https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2024-financial-year-provisional/Download-data/annual-enterprise-survey-2024-financial-year-provisional.csv
Resolving www.stats.govt.nz (www.stats.govt.nz)... 45.60.15.134
Connecting to www.stats.govt.nz (www.stats.govt.nz)|45.60.15.134|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8795771 (8.4M) [application/octet-stream]
Saving to: ‘annual-enterprise-survey-2024-financial-year-provisional.csv’

annual-enterprise-s 100%[===================>]   8.39M  6.94MB/s    in 1.2s

2025-08-10 05:49:15 (6.94 MB/s) - ‘annual-enterprise-survey-2024-financial-year-provisional.csv’ saved [8795771/8795771]

In [18]:
df = pd.read_csv('annual-enterprise-survey-2024-financial-year-provisional.csv')
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [20]:
!pip install --upgrade gdown
!gdown --fuzzy "https://drive.google.com/file/d/1ckdwGO7fqvOHd3WIZ654GWyOgzqfsxQW/view?usp=sharing" --output business.csv

Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.18.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.14.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2025.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (1.7.1)
Downloading...
From: https://drive.google.com/uc?id=1ckdwGO7fqvOHd3WIZ654GWyOgzqfsxQW
To: /content/business.csv
100% 681k/681k [00:00<00:00, 113MB/s]

In [22]:
df=pd.read_csv('business.csv')
df.info()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 100: invalid start byte

https://docs.google.com/spreadsheets/d/1klwILL7lp1isiMKPHuqJfEi-ZtyZUfiz/edit?usp=sharing&ouid=101245696759654643056&rtpof=true&sd=true

In [24]:
!pip install --upgrade gdown
!gdown --fuzzy "https://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1klwILL7lp1isiMKPHuqJfEi-ZtyZUfiz%2Fedit%3Fusp%3Dsharing%26ouid%3D101245696759654643056%26rtpof%3Dtrue%26sd%3Dtrue" --output business_report.csv
df=pd.read_csv('business_report.csv')
df.info()

Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.18.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.14.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2025.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (1.7.1)
Downloading...
From: https://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1klwILL7lp1isiMKPHuqJfEi-ZtyZUfiz%2Fedit%3Fusp%3Dsharing%26ouid%3D101245696759654643056%26rtpof%3Dtrue%26sd%3Dtrue
To: /content/business_report.csv
17.6kB [00:00, 520kB/s]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 83 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  --------------  -----

In [26]:
!git clone http://wilmabainbridge.com/facememorability2.html

Cloning into 'facememorability2.html'...
fatal: repository 'http://wilmabainbridge.com/facememorability2.html/' not found